### ISSUE TITLE
Your Twitter link doesn't work

### ISSUE THREAD

**Issue by alexellis** [jonakoudijs/jona.io#7]
Hi, I saw you star the openfaas repo and checked out your profile. Btw your Twitter link doesn't work 🙂 

Did you know?

Alex

**Comment by jonakoudijs** [comment]
Hi Alex,

Thank for letting me know! I deleted my Twitter account a while ago and totally forgot to update my website :) it's a great piece of software btw. Awesome work you are doing.

Jona


PS.
I removed the Twitter reference ;)
